README.md, backends/cardano-graphql/src/main/java/com/bloxbean/cardano/client/backend/gql/GqlAssetService.java, src/integration-test/java/com/bloxbean/cardano/client/backend/impl/blockfrost/service/BFAssetServiceIT.java, src/main/java/com/bloxbean/cardano/client/backend/api/AssetService.java, src/main/java/com/bloxbean/cardano/client/backend/impl/blockfrost/service/BFAssetService.java, src/main/java/com/bloxbean/cardano/client/backend/impl/blockfrost/service/http/AssetsApi.java, src/main/java/com/bloxbean/cardano/client/backend/model/AssetAddress.java, src/main/java/com/bloxbean/cardano/client/backend/model/PolicyAsset.java, src/main/java/com/bloxbean/cardano/client/crypto/Keys.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/script/RequireTimeBefore.java, src/test/java/com/bloxbean/cardano/client/crypto/KeyGenUtilTest.java, src/test/java/com/bloxbean/cardano/client/transaction/spec/script/ScriptTest.java
Default Constructor for Deserialization.
=> Keys.java, RequireTimeBefore.java Serialization/Deserialization Fix + AssetService Expansion + Updated Used By Section

backend-modules/koios/build.gradle
Changelog:
https://github.com/cardano-community/koios-java-client/releases/tag/v.1.6-alpha
=> Bump Koios Java Lib to 1.6

src/main/java/com/bloxbean/cardano/client/cip/cip30/CIP30Constant.java, src/main/java/com/bloxbean/cardano/client/cip/cip30/CIP30DataSigner.java, src/main/java/com/bloxbean/cardano/client/cip/cip30/DataSignature.java, src/main/java/com/bloxbean/cardano/client/cip/cip8/HeaderMap.java, src/test/java/com/bloxbean/cardano/client/cip/cip30/DataSignatureTest.java
- Added methods to get address bytes, public key, curve from DataSignature
- Moved CIP30 values to a separate class
- Helper methods to get headers in HeaderMap
=> Helper methods in DataSignature

src/main/java/com/bloxbean/cardano/client/crypto/bip32/HdKeyGenerator.java, src/test/java/com/bloxbean/cardano/client/crypto/bip32/HdKeyGeneratorTest.java
Added the function and test mentioned in https://github.com/bloxbean/cardano-client-lib/issues/46 to the code for a pull request
=> Implemented getChildPublicKey for xPub key derivation

integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/EpochServiceIT.java, src/main/java/com/bloxbean/cardano/client/api/model/ProtocolParams.java, src/test/resources/protocol-params.json
- Added coinsPerUtxoSize
- Added Deprecated annotation to coinsPerUtxoWord
=> [#134] Added coinsPerUtxoSize field to protocol params

integration-test/src/it/java/com/bloxbean/cardano/client/function/ContractV2TxBuilderContextITTest.java, src/main/java/com/bloxbean/cardano/client/function/Output.java, src/main/java/com/bloxbean/cardano/client/function/helper/OutputBuilders.java, src/main/java/com/bloxbean/cardano/client/function/helper/ScriptDataHashCalculator.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/CostMdls.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/PlutusV1Script.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/PlutusV2Script.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/TransactionOutput.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/TransactionWitnessSet.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/script/NativeScript.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/script/Script.java, src/test/java/com/bloxbean/cardano/client/address/AddressServiceTest.java, src/test/java/com/bloxbean/cardano/client/transaction/spec/TransactionOutputTest.java
- Fixed script ref issue
- New integration tests
=> Script Ref fix

backend-modules/koios/build.gradle, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/Constants.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAccountService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAddressService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAssetService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosBackendService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosBlockService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosEpochService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosMetadataService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosNetworkService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosTransactionService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosUtxoService.java, backend/src/main/java/com/bloxbean/cardano/client/backend/api/AssetService.java, backend/src/test/java/com/bloxbean/cardano/client/backend/BaseTest.java, build.gradle, integration-test/build.gradle, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/BaseITTest.java, src/main/java/com/bloxbean/cardano/client/crypto/api/SigningProvider.java
=> Apply Koios 1.13 Schema Changes

backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/common/Constants.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/helper/PoolRegistrationIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/helper/UpdateTransactionIT.java, src/main/java/com/bloxbean/cardano/client/crypto/KeyGenUtil.java, src/main/java/com/bloxbean/cardano/client/function/helper/SignerProviders.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/Update.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/cert/GenesisKeyDelegation.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/cert/MoveInstataneous.java, src/main/java/com/bloxbean/cardano/client/transaction/spec/cert/PoolRegistration.java, src/test/java/com/bloxbean/cardano/client/crypto/KeyGenUtilTest.java, src/test/java/com/bloxbean/cardano/client/function/helper/SignerProvidersTest.java
Added support for missing transaction types :
- Pool Registration, Protocol Param Update, Genesis Key delegation, MoveInstataneous 
Added prepod & preview endpoints for Blockfrost backend
=> Missing txn types and other changes

src/main/java/com/bloxbean/cardano/client/transaction/spec/PlutusData.java
Proposing a unit constructor for redeemers.
=> Static unit Plutus data (often used for redeemers)

backend-modules/ogmios/src/it/java/com/bloxbean/cardano/client/backend/ogmios/TxBuilderContextTest.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AccountServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AddressServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AssetServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/BlockServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/EpochServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/MetadataServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/TransactionServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/helper/StakeTransactionIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/helper/TransactionHelperServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/function/ContractTxBuilderContextITTest.java, integration-test/src/it/java/com/bloxbean/cardano/client/function/ContractV2TxBuilderContextITTest.java, integration-test/src/it/java/com/bloxbean/cardano/client/function/TxBuilderContextTest.java
=> Integration test fixes for preprod

backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/BFAccountService.java, backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/BFAssetService.java, backend-modules/koios/src/it/java/com/bloxbean/cardano/client/backend/koios/it/KoiosAccountServiceIT.java, backend-modules/koios/src/it/java/com/bloxbean/cardano/client/backend/koios/it/KoiosAssetServiceIT.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAccountService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAssetService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosTransactionService.java, backend/src/main/java/com/bloxbean/cardano/client/backend/api/AccountService.java, backend/src/main/java/com/bloxbean/cardano/client/backend/api/AssetService.java, cip/cip25/src/main/java/com/bloxbean/cardano/client/cip/cip25/NFT.java, cip/cip25/src/main/java/com/bloxbean/cardano/client/cip/cip25/NFTFile.java, cip/cip25/src/main/java/com/bloxbean/cardano/client/cip/cip25/NFTProperties.java, cip/cip25/src/test/java/com/bloxbean/cardano/client/cip/cip25/NFTMetadataTest.java, cip/cip27/src/main/java/com/bloxbean/cardano/client/cip/cip27/RoyaltyToken.java, cip/cip27/src/main/java/com/bloxbean/cardano/client/cip/cip27/RoyaltyTokenMetadata.java, cip/cip30/src/main/java/com/bloxbean/cardano/client/cip/cip30/CIP30UtxoSupplier.java, cip/cip30/src/test/java/com/bloxbean/cardano/client/cip/cip30/CIP30UtxoSupplierTest.java, core/src/main/java/com/bloxbean/cardano/client/api/model/Utxo.java, core/src/main/java/com/bloxbean/cardano/client/transaction/spec/Value.java, core/src/test/java/com/bloxbean/cardano/client/api/helper/impl/RandomImproveUtxoTransactionBuilderTest.java, core/src/test/java/com/bloxbean/cardano/client/api/helper/impl/UtxoTransactionBuilderTest.java, core/src/test/java/com/bloxbean/cardano/client/api/model/UtxoTest.java, docs/docs/gettingstarted/build.md, docs/docs/gettingstarted/key-apis.md, docs/docs/gettingstarted/multisig-quickstart.md, docs/docs/gettingstarted/tokens-distribution.md, gradle/libs.versions.toml, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AccountServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AssetServiceIT.java, integration-test/src/it/java/com/bloxbean/cardano/client/cip/CIP25NFTTransactionITTest.java
- [New Tokens Distribution Guide + Example](https://github.com/bloxbean/cardano-client-lib/commit/b0a4320e7957cd4dac651e3d9ac444b9a3c5fa5a)
- [NFT Metadata Enhancement to Support a metadata field value for Map values of type List](https://github.com/bloxbean/cardano-client-lib/commit/1d5a2697d946d4b40f0bef32c5b263db9b7c3e24)
- [Add New Services Methods: getAllAccountAddresses, getAllAccountAssets, getAllAssetAddresses, getAllPolicyAssets](https://github.com/bloxbean/cardano-client-lib/commit/0ab0324239c298f2ec338e05fa610bf625650537)
- [Bump Koios Java Client to 1.16.1 (TransactionContent Mapping Fix)](https://github.com/bloxbean/cardano-client-lib/commit/fbc53b8a8b5ecd49dc493997e8f54a4484eb3080)
=> Enhancements and Koios Bump to 1.16.1

function/src/main/java/com/bloxbean/cardano/client/function/helper/RedeemerUtil.java, function/src/test/java/com/bloxbean/cardano/client/function/helper/RedeemerUtilTest.java, integration-test/src/it/java/com/bloxbean/cardano/client/function/RedeemerUtilSortingInputsITTest.java
New sorting logic handles txId and index separately.
=> [#201] Fixed inputs sorting

README.md, docs/docs/intro.md
=> Fix: typos

core/src/main/java/com/bloxbean/cardano/client/plutus/impl/DefaultPlutusObjectConverter.java, core/src/test/java/com/bloxbean/cardano/client/plutus/DefaultPlutusObjectConverterTest.java
- Support for Optional types with tests
=> Fix(#223): Added support for Optional types

function/src/main/java/com/bloxbean/cardano/client/function/helper/InputBuilders.java, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/BaseITTest.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxIT.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/StakeTxIT.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/AbstractTx.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/ScriptTx.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/Tx.java, quicktx/src/test/java/com/bloxbean/cardano/client/quicktx/TxTest.java
- Mint asset api cleanup
- Burn token support through same mintAsset api
- QuickTx integration tests with DEVKIT
=> refactor: mintAssets api cleanup. QuickTx integration tests with DEVKIT.

backend-modules/ogmios/build.gradle, backend-modules/ogmios/src/it/java/com/bloxbean/cardano/client/backend/ogmios/KupmiosBackendServiceTest.java, backend-modules/ogmios/src/it/java/com/bloxbean/cardano/client/backend/ogmios/OgmiosBaseTest.java, backend-modules/ogmios/src/main/java/com/bloxbean/cardano/client/backend/ogmios/KupmiosBackendService.java, backend-modules/ogmios/src/main/java/com/bloxbean/cardano/client/backend/ogmios/OgmiosBackendService.java, backend-modules/ogmios/src/main/java/com/bloxbean/cardano/client/backend/ogmios/OgmiosTransactionService.java, quicktx/build.gradle
- To fix #295 
- New ``KupmiosBackendService`` which combines both Ogmios (for tx submission & evaluation) and Kupo (for utxo service) through one single backend interface.
=> fix: #295 Class cast exception during evaluateTx.

function/src/main/java/com/bloxbean/cardano/client/function/helper/InputBuilders.java, function/src/main/java/com/bloxbean/cardano/client/function/helper/OutputBuilders.java, function/src/main/java/com/bloxbean/cardano/client/function/helper/ScriptUtxoFinders.java, plutus/src/main/java/com/bloxbean/cardano/client/plutus/spec/PlutusData.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxIT.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/ScriptTx.java
To fix #298
- Add datum to witness list
- Removed checked exception for getDatumHash() & getDatumHashBytes()
=> Added collectFrom() methods with datum for V1

quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxIT.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java, quicktx/src/test/java/com/bloxbean/cardano/client/quicktx/TxTest.java
#299 
**New methods**
- withRequiredSigner(Address... addresses)
- withRequiredSigner(byte[]... credentials)
=> feat: #299 Methods to add required signers

annotation-processor/build.gradle, gradle/libs.versions.toml
Guava : 32.1.2-jre
jackson-databind: 2.15.0
yaci: 0.2.0
aiken-java-binding: 0.0.8
=> chore: Bump guava, jackson, yaci, aiken-java-binding versions

quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ParameterizedScriptIT.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxIT.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/TestDataBaseIT.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/ScriptTx.java
New methods
- ScriptTx.collectFrom(utxo)
- ScriptTx.collectFrom(utxos)
- QuickTxBuilder.ignoreScriptCostEvaluationError()  to decide if an exception is thrown during script cost evaluation or not.
=> ScriptTx: Method to add utxo without redeemer

annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/ClassDefinitionGenerator.java, annotation-processor/src/test/resources/A.java, annotation-processor/src/test/resources/AnotherData.java
#316 
- byte[] field type checking was not correct
=> fix: 316 checking byte[] type

docs/docs/usedby.md
=> Add used by 'nftio.io'

backend-modules/koios/src/it/java/com/bloxbean/cardano/client/backend/koios/it/KoiosScriptServiceIT.java, backend-modules/koios/src/it/java/com/bloxbean/cardano/client/backend/koios/it/KoiosUtxoServiceIT.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosBackendService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosBlockService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosEpochService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosScriptService.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosUtxoService.java, common/src/main/java/com/bloxbean/cardano/client/util/StringUtils.java, gradle/libs.versions.toml, integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/UtxoServiceIT.java, plutus/src/main/java/com/bloxbean/cardano/client/plutus/spec/PlutusScript.java
Fixes #322, #323 (tx_index is not supported yet in Asset Transaction Model)
=> Koios Java Client Upgrade to 1.17.3

annotation-processor/build.gradle, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/ClassDefinitionGenerator.java, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/ConverterCodeGenerator.java, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/model/ClassDefinition.java, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/model/Field.java, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/model/FieldType.java, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/model/JavaType.java, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/model/Type.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/ConstrAnnotationProcessorTest.java, annotation-processor/src/test/resources/A.java, annotation-processor/src/test/resources/Model1.java, annotation-processor/src/test/resources/NestedListMapModel.java, annotation-processor/src/test/resources/NestedListModel.java, annotation-processor/src/test/resources/NestedMapModel.java, build.gradle, gradle/libs.versions.toml, plutus/src/main/java/com/bloxbean/cardano/client/plutus/annotation/BasePlutusDataConverter.java
- Added support for Boolean
- Nested List
- Nested Map
- Complex Nested Objects
- serialize, serializeToHex, deserialize methods
=> Enhance annotation processor

annotation-processor/build.gradle, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/ConverterCodeGenerator.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/BasicModelTest.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/NestedBasicModelTest.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/NestedListModelTest.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/StudentTest.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/model/A.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/model/BasicModel.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/model/NestedBasicModel.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/model/NestedModel.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/model/Student.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/model/Subject.java, annotation-processor/src/test/java/com/bloxbean/cardano/client/plutus/annotation/model/Vote.java, plutus/src/main/java/com/bloxbean/cardano/client/plutus/annotation/BasePlutusDataConverter.java, quicktx/build.gradle
- Annotation processor code generation tests
=> Tests for Annotation processor

README.md
Added prerequisites to readme when building from source.
=> adding prerequisites to readme

transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/governance/actions/ParameterChangeAction.java, transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/governance/actions/TreasuryWithdrawalsAction.java
- Added policy hash to Parameter Change and Treasury Withdrawal Gov Action
=> fix: #388 Added policy hash

backend-modules/koios/README.md
- Updated the example in the README to match the current implementation
=> chore: update Koios backend example in README.md

annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/DataImplGenerator.java, annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/blueprint/ValidatorProcessor.java, plutus/src/main/java/com/bloxbean/cardano/client/plutus/blueprint/model/Data.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/annotation/HelloWorldValidatorTest.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/annotation/MintValidatorTest.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/AbstractTx.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/ScriptTx.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/blueprint/extender/LockUnlockValidatorExtender.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/blueprint/extender/MintValidatorExtender.java
- New static helper methods in Data class 
`static fromPlutusData(ConstrPlutusData)`, `deserialize(bytes)`, `deserialize(hex)`
- New methods in LockUnlock and Mint extenders
- Fix incorrect redeemer index issue when a ScriptTx is composed with another Tx or ScriptTx
=> Blueprint Code generation enhancements

core/src/main/java/com/bloxbean/cardano/client/account/Account.java, core/src/test/java/com/bloxbean/cardano/client/account/AccountCIP105KeysTest.java, core/src/test/java/com/bloxbean/cardano/client/account/CIP105TestVector.java, crypto/src/main/java/com/bloxbean/cardano/client/crypto/cip1852/DerivationPath.java, function/src/main/java/com/bloxbean/cardano/client/function/helper/SignerProviders.java, governance/README.md, governance/src/main/java/com/bloxbean/cardano/client/governance/DRepId.java, governance/src/main/java/com/bloxbean/cardano/client/governance/keys/CommitteeColdKey.java, governance/src/main/java/com/bloxbean/cardano/client/governance/keys/CommitteeHotKey.java, governance/src/main/java/com/bloxbean/cardano/client/governance/keys/DRepKey.java, governance/src/test/java/com/bloxbean/cardano/client/governance/DRepIdTest.java, governance/src/test/java/com/bloxbean/cardano/client/governance/keys/CommitteeColdKeyTest.java, governance/src/test/java/com/bloxbean/cardano/client/governance/keys/CommitteeHotKeyTest.java, governance/src/test/java/com/bloxbean/cardano/client/governance/keys/DRepKeyTest.java
https://github.com/cardano-foundation/CIPs/tree/master/CIP-0105
- New classes
- DRepKey
- CommitteeColdKey
- CommitteeHotKey
- New methods in `Account` to get governance keys and sign methods for the new keys
=> feat: #368 CIP105 - Governance keys derivation and bech32 encoding

backend/src/main/java/com/bloxbean/cardano/client/backend/api/DefaultScriptSupplier.java
=> fix: Handle null or empty scriptHash in getScript method

backend-modules/koios/src/it/java/com/bloxbean/cardano/client/backend/koios/it/KoiosEpochServiceIT.java, backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosEpochService.java
Updated `KoiosEpochService` to handle and return cost models for PlutusV3.
Added corresponding assertions in `KoiosEpochServiceIT` to ensure PlutusV3 cost model integrity.
=> Add PlutusV3 cost model handling

plutus/src/main/java/com/bloxbean/cardano/client/plutus/spec/MapPlutusData.java
=> Switch to LinkedHashMap to keep the same iteration order during deserialization

common-spec/src/main/java/com/bloxbean/cardano/client/spec/Script.java, core-api/src/main/java/com/bloxbean/cardano/client/api/util/ReferenceScriptUtil.java, core-api/src/test/java/com/bloxbean/cardano/client/api/util/ReferenceScriptUtilTest.java, function/src/main/java/com/bloxbean/cardano/client/function/helper/DuplicateScriptWitnessChecker.java, plutus/src/main/java/com/bloxbean/cardano/client/plutus/spec/PlutusScript.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/AbstractTx.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java, transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/NativeScript.java
Reorganized serialization and deserialization methods across Script, PlutusScript, and NativeScript classes. Updated tests to verify the correct handling of multiple script types, including PlutusV1, PlutusV2, PlutusV3, and NativeScript.
=> Handle NativeScript as ScriptRef

common-spec/src/main/java/com/bloxbean/cardano/client/spec/Script.java, core-api/src/main/java/com/bloxbean/cardano/client/api/util/ReferenceScriptUtil.java, core-api/src/test/java/com/bloxbean/cardano/client/api/util/ReferenceScriptUtilTest.java, function/src/main/java/com/bloxbean/cardano/client/function/helper/DuplicateScriptWitnessChecker.java, plutus/src/main/java/com/bloxbean/cardano/client/plutus/spec/PlutusScript.java, quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/AbstractTx.java, quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java, transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/NativeScript.java
Reverts bloxbean/cardano-client-lib#456
=> Revert "Handle NativeScript as ScriptRef"

transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/TransactionSigner.java
- Make `addWitnessToTransaction` method public in `TransactionSigner`
=> Make addWitnessToTransaction method public

gradle.properties, gradle/libs.versions.toml
- Update dependency to bloxbean fork of ed25519-java lib
=> Update edsa lib dependency to bloxbean fork 

function/src/main/java/com/bloxbean/cardano/client/function/helper/FeeCalculators.java
To fix #498 
- Use dummy key and signature bytes for additional signers instead of generating new dummy accounts.
- Update the last two bytes of the dummy key and signature to ensure uniqueness.
=> fix: #498 Use dummy key and signature for additional signers instead of generating new dummy accounts

transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/ScriptAll.java, transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/ScriptAny.java, transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/ScriptAtLeast.java, transaction-spec/src/test/java/com/bloxbean/cardano/client/transaction/spec/script/ScriptTest.java
PR to merge the native script parse error fix to master
check https://github.com/bloxbean/cardano-client-lib/pull/503
=> fix: Native script parsing issue when indefinite-length array is used.

quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/Tx.java
=> #497 Add support for attaching native scripts to transactions

docs/docs/gettingstarted/account-setup.md, docs/docs/gettingstarted/dependencies.md, docs/docs/gettingstarted/multisig-quickstart.md, docs/docs/gettingstarted/simple-transfer.md, docs/docs/intro.md
issue: https://github.com/bloxbean/cardano-client-lib/issues/515
=> docs: fix deprecated apis for version 0.7.0

gradle/libs.versions.toml, metadata/build.gradle, metadata/src/main/java/com/bloxbean/cardano/client/metadata/MetadataBuilder.java, metadata/src/main/java/com/bloxbean/cardano/client/metadata/helper/AbstractMetadataConverter.java, metadata/src/main/java/com/bloxbean/cardano/client/metadata/helper/JsonNoSchemaToMetadataConverter.java, metadata/src/main/java/com/bloxbean/cardano/client/metadata/helper/JsonNodeToMetadataConverter.java, metadata/src/main/java/com/bloxbean/cardano/client/metadata/helper/MetadataToJsonNoSchemaConverter.java, metadata/src/main/java/com/bloxbean/cardano/client/metadata/helper/MetadataToYamlNoSchemaConverter.java, metadata/src/main/java/com/bloxbean/cardano/client/metadata/helper/YamlNoSchemaToMetadataConverter.java, metadata/src/test/java/com/bloxbean/cardano/client/metadata/MetadataBuilderYamlTest.java
- Add helpers to convert Metadata to Yaml and Yaml to Metadata
- Move common methods to a base class
=> feat: Convert Metadata <--> Yaml

README.md
Updated versions in README for stable and snapshot releases.
=> Update version numbers in README.md
