bloxbean/cardano-client-lib

src/main/java/com/bloxbean/cardano/client/account/Account.java
src/main/java/com/bloxbean/cardano/client/crypto/bip32/HdKeyGenerator.java
src/main/java/com/bloxbean/cardano/client/crypto/cip1852/CIP1852.java
src/main/java/com/bloxbean/cardano/client/crypto/cip1852/DerivationPath.java
src/test/java/com/bloxbean/cardano/client/account/AccountTest.java

Allow to create an Account from a private key because it's not always possible to have the seed available and it's safer/faster to derive from the account hardened key.

Allow to create an Account from a private key

---

src/main/java/com/bloxbean/cardano/client/common/MinAdaCalculator.java

Add data hash calculation for MinAdaCalculator, according to https://github.com/input-output-hk/cardano-ledger/blob/master/doc/explanations/min-utxo-alonzo.rst

Add data hash calculation for MinAdaCalculator

---

src/main/java/com/bloxbean/cardano/client/backend/api/helper/TransactionHelperService.java
src/main/java/com/bloxbean/cardano/client/backend/api/helper/impl/UtxoTransactionBuilderImpl.java
src/main/java/com/bloxbean/cardano/client/coinselection/UtxoSupplier.java
src/main/java/com/bloxbean/cardano/client/coinselection/impl/DefaultUtxoSelectionStrategyImpl.java
src/main/java/com/bloxbean/cardano/client/coinselection/impl/DefaultUtxoSupplier.java
src/main/java/com/bloxbean/cardano/client/coinselection/impl/LargestFirstUtxoSelectionStrategy.java
src/main/java/com/bloxbean/cardano/client/coinselection/impl/RandomImproveUtxoSelectionStrategy.java
src/test/java/com/bloxbean/cardano/client/backend/api/helper/impl/RandomImproveUtxoTransactionBuilderTest.java
src/test/java/com/bloxbean/cardano/client/coinselection/impl/LargestFirstUtxoSelectionStrategyImplTest.java
src/test/java/com/bloxbean/cardano/client/coinselection/impl/RandomImproveUtxoSelectionStrategyTest.java
src/test/java/com/bloxbean/cardano/client/function/helper/InputBuildersTest.java

- Added `UtxoSupplier` for supplying UTXOs to the UtxoSelectionStrategy. 
- Added `DefaultUtxoSupplier` which uses existing UtxoService for providing UTXOs
The aim of this PR is to provide abstraction in preparation of splitting the code into different modules (core, api, backends) where `UtxoSupplier` remains in `core` and `UtxoService` moves to `api`.

UTXO supplier abstraction

---

src/main/java/com/bloxbean/cardano/client/transaction/spec/Policy.java

Policy Id shouldn't be ignored because it is better not to add serialization capabilities in frontend apps (better performance)

Remove JsonIgnore Annotation from getPolicyId()

---

src/main/java/com/bloxbean/cardano/client/transaction/spec/BigIntPlutusData.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/BytesPlutusData.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/ConstrPlutusData.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/ListPlutusData.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/MapPlutusData.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/PlutusData.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/BigIntDataJsonDeserializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/BigIntDataJsonSerializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/BytesDataJsonDeserializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/BytesDataJsonSerializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/ConstrDataJsonDeserializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/ConstrDataJsonSerializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/ListDataJsonDeserializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/ListDataJsonSerializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/MapDataJsonDeserializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/MapDataJsonSerializer.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/PlutusDataJsonConverter.java
src/main/java/com/bloxbean/cardano/client/transaction/spec/serializers/PlutusDataJsonKeys.java
src/main/java/com/bloxbean/cardano/client/util/JsonUtil.java
src/test/java/com/bloxbean/cardano/client/transaction/spec/MapPlutusDataTest.java
src/test/java/com/bloxbean/cardano/client/transaction/spec/serializers/BigIntDataJsonSerializerTest.java
src/test/java/com/bloxbean/cardano/client/transaction/spec/serializers/BytesDataJsonSerializerTest.java
src/test/java/com/bloxbean/cardano/client/transaction/spec/serializers/ConstrDataJsonSerializerTest.java
src/test/java/com/bloxbean/cardano/client/transaction/spec/serializers/ListDataJsonSerializerTest.java
src/test/java/com/bloxbean/cardano/client/transaction/spec/serializers/MapDataJsonSerializerTest.java
src/test/java/com/bloxbean/cardano/client/transaction/spec/serializers/PlutusDataJsonConverterTest.java

Added support for
- PlutusData to Json
- Json to PlutusData
- Added custom serializers to support json conversion (Detail schema based)
Refer to below links for format details
https://github.com/input-output-hk/cardano-node/blob/master/cardano-api/src/Cardano/Api/ScriptData.hs#L254
https://github.com/Emurgo/cardano-serialization-lib/blob/2b775e8b92331885d4caf2f4a579ba86c69eea61/rust/src/plutus.rs#L1009
Usage:
```
//To json
String json = PlutusDataJsonConverter.toJson(plutusData);
//From json
PlutusData dePlutusData = PlutusDataJsonConverter.toPlutusData(json)
```

Function to serialize datum hex to json format 

---

function/src/main/java/com/bloxbean/cardano/client/function/helper/InputBuilders.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/InputBuildersTest.java
integration-test/src/it/java/com/bloxbean/cardano/client/function/ContractTxBuilderContextITTest.java
integration-test/src/it/java/com/bloxbean/cardano/client/function/ContractV2TxBuilderContextITTest.java

- Deprecated following methods
```
createFromUtxos(List<Utxo> utxos)
```
```
createFromUtxos(Supplier<List<Utxo>> supplier)
```

[#205] Deprecated createFromUtxos(List<Utxo>) method and updated tests

---

function/src/main/java/com/bloxbean/cardano/client/function/helper/BalanceTxBuilders.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/BalanceTxBuildersTest.java

Fix for #222
Call changeAdjustment before collateral calculation to calculate accurate totalCollateral.
The following calls are happening balanceTx.
1.  Fee calculation
2. ChangeAdjustement call to check if minAda requirement is met and add additional inputs with updated fee
3. Total collateral calculation and update value in collateral output

Fix insufficient collateral due to new inputs in change adjustment calculation in balanceTx

---

build.gradle
gradle.properties
plutus/src/main/java/com/bloxbean/cardano/client/plutus/util/PlutusUtil.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java

Some quick fixes:
1. Change scope of TxContext to public
2. Utility class to double cbor encode. It is required for aiken compiled code.

0.5.0 alpha fix

---

core-api/src/main/java/com/bloxbean/cardano/client/api/model/Amount.java
quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/Verifier.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/VerifierException.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/verifiers/OutputAmountVerifier.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/verifiers/TxVerifiers.java
quicktx/src/test/java/com/bloxbean/cardano/client/quicktx/verifiers/OutputAmountVerifierTest.java
quicktx/src/test/java/com/bloxbean/cardano/client/quicktx/verifiers/TxVerifiersTest.java

To fix #259 
- Added a new method ```withVerifier(Verifier)``` to provide Verifier or chain of verifiers to verify the transaction before submission.
- TxVerifiers helper to provide out-of-box verifier for output amount for an address
- Application can implement ``Verifier`` interface to provide application specific custom verifiers.
- VerificationException is thrown when verification fails
Example:
```
import static com.bloxbean.cardano.client.quicktx.verifiers.TxVerifiers.outputAmountVerifier;
...
Result<String> result = quickTxBuilder.compose(tx1, tx2)
.withSigner(SignerProviders.signerFrom(sender1))
.withSigner(SignerProviders.signerFrom(policy))
.withVerifier(
outputAmountVerifier(receiver2, Amount.ada(3.0))
.andThen(outputAmountVerifier(receiver3, Amount.ada(2.13))) …
```

Support to verify the transaction content before submission through Verifier(s) 

---

function/src/main/java/com/bloxbean/cardano/client/function/TxBuilderContext.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/InputBuilders.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/OutputBuilders.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/InputBuildersTest.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/OutputBuildersTest.java
function/src/test/resources/utxos-function.json
integration-test/src/it/java/com/bloxbean/cardano/client/function/TxBuilderContextIT.java
quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilderIT.java
quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxIT.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java

To fix #285 and enhancement
1. Added the ``mergeOutputs`` method to the ``TxBuilderContext`` of the Composable Function API. By default, this is set to true, meaning that outputs with the same address will be merged together. If mergeOutputs is set to false, the final outputs will remain as defined by the application.
2. Added the mergeOutputs method to the QuickTxBuilder of QuickTx. By default, this is also true. The behavior is exactly the same as in the first point.
Defined outputs and TxBuilder
```
Output mintOutput = Output.builder()
.address(senderAddress)
.policyId(policy.getPolicyId())
.assetName("TestNFT")
.qty(BigInteger.valueOf(100))
.build();
Output feeOutput = Output.builder()
.address(receiver1)
.assetName(LOVELACE)
.qty(adaToLovelace(1))
.build();
//Create TxBuilder …
```

Add mergeOutputs option to control whether to merge outputs or not

---

address/src/main/java/com/bloxbean/cardano/client/address/AddressProvider.java
backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/BFAssetService.java
backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/http/AssetsApi.java
backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAssetService.java
backend/src/main/java/com/bloxbean/cardano/client/backend/api/AssetService.java
backend/src/main/java/com/bloxbean/cardano/client/backend/model/AssetTransactionContent.java
common/src/main/java/com/bloxbean/cardano/client/util/Tuple.java
integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AssetServiceIT.java

- added `getTransactions` to `AssetService` (https://docs.blockfrost.io/#tag/Cardano-Assets/paths/~1assets~1%7Basset%7D~1transactions/get)
this method is particularly useful for efficiently fetching DEX pool txs
- add `@ToString` and `@EqualsAndHashCode` to `com.bloxbean.cardano.client.util.Tuple`
for easier debugging and comparing
- changed visibility of 1 `AddressProvider` method
for easier conversion of stake and payment key hash to address

Added AssetService.getTransactions, added Tuple.toString + equals & hashCode, change AddressProvider visibility

---

transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/Asset.java
transaction-spec/src/test/java/com/bloxbean/cardano/client/transaction/spec/AssetSpecTest.java

Hi @satran004 , I've fixed for issue #339. Could you take a look at this PR?

fix: #339 handle when asset name is invalid hex string

---

backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosUtxoService.java

Error occured when page > 1 was requested, but not enough elements are available. So page 2 must be empty for example.

#360 fixed getSubListByPage. 

---

quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/GovTx.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/Tx.java

- Set default drep registration deposit amount to 500 ADA (same as current value in Sanchnet)
- Added a new method `drepRegistration() `to take drep registration deposit as parameter.

fix: Update default drep registration amount to 500 ADA as per current settings in protocol param

---

backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/BFAccountService.java
backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/BFAddressService.java
backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/BFBackendService.java
backend-modules/koios/src/it/java/com/bloxbean/cardano/client/backend/koios/it/KoiosAccountServiceIT.java
backend-modules/koios/src/it/java/com/bloxbean/cardano/client/backend/koios/it/KoiosAddressServiceIT.java
backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAccountService.java
backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosAddressService.java
backend/src/main/java/com/bloxbean/cardano/client/backend/api/AccountService.java
backend/src/main/java/com/bloxbean/cardano/client/backend/api/AddressService.java
integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AccountServiceIT.java
integration-test/src/it/java/com/bloxbean/cardano/client/backend/api/AddressServiceIT.java

Fix Wrong handling for Address Transactions functionality for Koios Provider
Note: Koios Provider isn't supporting filling the tx_index field in the AddressTransactionContent object

New Koios + BF Support for resolving Transactions Data by Payment/Staking Addresses

---

backend/src/main/java/com/bloxbean/cardano/client/backend/api/DefaultScriptSupplier.java
common/src/main/java/com/bloxbean/cardano/client/util/CheckedFunction.java
common/src/main/java/com/bloxbean/cardano/client/util/ResultWrapper.java
common/src/main/java/com/bloxbean/cardano/client/util/Try.java
core-api/src/main/java/com/bloxbean/cardano/client/api/ScriptSupplier.java
core-api/src/main/java/com/bloxbean/cardano/client/api/model/ProtocolParams.java
core-api/src/main/java/com/bloxbean/cardano/client/api/model/ResultWrapper.java
core-api/src/main/java/com/bloxbean/cardano/client/api/util/ReferenceScriptUtil.java
core-api/src/test/java/com/bloxbean/cardano/client/api/util/ReferenceScriptUtilTest.java
core/src/main/java/com/bloxbean/cardano/client/api/helper/FeeCalculationService.java
core/src/main/java/com/bloxbean/cardano/client/api/helper/impl/FeeCalculationServiceImpl.java
core/src/test/java/com/bloxbean/cardano/client/api/helper/impl/FeeCalculationServiceTest.java
core/src/test/resources/protocol-params.json
function/src/main/java/com/bloxbean/cardano/client/function/TxBuilderContext.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/FeeCalculators.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/FeeCalculatorsTest.java
function/src/test/resources/protocol-params.json
quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxIT.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/ScriptTx.java

Reference: https://github.com/IntersectMBO/cardano-ledger/blob/e77d4032a0b305baeabd5997df977ae579b2316e/eras/conway/impl/src/Cardano/Ledger/Conway/Tx.hs#L93

feat: #411 tier ref script fee implementation for Conway era

---

common/src/main/java/com/bloxbean/cardano/client/common/model/SlotConfig.java
common/src/main/java/com/bloxbean/cardano/client/common/model/SlotConfigs.java

Currently local transaction evaluators like AikentTransactionEvalutator and ScalusTE, only work for mainnet in case of contracts which require time interval validaiton.
This PR contribute to fix https://github.com/bloxbean/cardano-client-lib/issues/429

Introduced SlotConfigs for Transaction Evaluators

---

annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/blueprint/BlueprintAnnotationProcessor.java
annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/blueprint/DataTypeProcessUtil.java
annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/blueprint/FieldSpecProcessor.java
annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/blueprint/ValidatorProcessor.java
annotation-processor/src/main/java/com/bloxbean/cardano/client/plutus/annotation/processor/util/JavaFileUtil.java

- Default Int type to `BigInteger`
- Package name to lowercase
#422

[Annotation Processor] Set default int type to BigInteger

---

gradle.properties

Removing the beta label prepares the library for a stable release.

Update version to 0.6.0 in gradle.properties

---

cip/cip30/src/main/java/com/bloxbean/cardano/client/cip/cip30/CIP30DataSigner.java
cip/cip30/src/test/java/com/bloxbean/cardano/client/cip/cip30/CIP30DataSignerTest.java
cip/cip8/src/main/java/com/bloxbean/cardano/client/cip/cip8/ProtectedHeaderMap.java
cip/cip8/src/main/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESign1Builder.java
cip/cip8/src/main/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESignBuilder.java
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESign1BuilderTest.java
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESignBuilderTest.java
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/cose_sign1_builder.rs
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/cose_sign_builder.rs

- Refactor `COSESignBuilder` and `COSESign1Builder` to handle external payloads and add support for payload hashing. 
- Update `CIP30DataSigner` logic to remove redundant hashed payload header. 
- Adjust tests to align with these changes and add new test files for Rust code comparisons.

Refactor COSESign builders for external payload and hashing

---

transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/RequireTimeAfter.java
transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/RequireTimeBefore.java
transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/script/ScriptAtLeast.java
transaction-spec/src/test/java/com/bloxbean/cardano/client/transaction/spec/script/ScriptTest.java

Enhanced RequireTimeBefore, RequireTimeAfter, and ScriptAtLeast to handle BigInteger values, allowing support for larger numeric ranges. Updated deserialization and serialization methods accordingly.
To fix #461

Support BigInteger for "required" in ScriptAtLeast and change slot from long to BigInteger

---

cip/cip30/src/main/java/com/bloxbean/cardano/client/cip/cip30/CIP30DataSigner.java
cip/cip30/src/test/java/com/bloxbean/cardano/client/cip/cip30/CIP30DataSignerTest.java
cip/cip8/src/main/java/com/bloxbean/cardano/client/cip/cip8/COSESign1.java
cip/cip8/src/main/java/com/bloxbean/cardano/client/cip/cip8/ProtectedHeaderMap.java
cip/cip8/src/main/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESign1Builder.java
cip/cip8/src/main/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESignBuilder.java
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESign1BuilderTest.java
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/COSESignBuilderTest.java
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/cose_sign1_builder.rs
cip/cip8/src/test/java/com/bloxbean/cardano/client/cip/cip8/builder/cose_sign_builder.rs
plutus/src/main/java/com/bloxbean/cardano/client/plutus/spec/MapPlutusData.java

Duplicate of https://github.com/bloxbean/cardano-client-lib/pull/453

feat: support for CIP-30 payload hash with an extra overloaded methods

---

backend-modules/koios/src/main/java/com/bloxbean/cardano/client/backend/koios/KoiosEpochService.java
gradle.properties
supplier/ogmios-supplier/src/main/java/com/bloxbean/cardano/client/supplier/ogmios/dto/ProtocolParametersDto.java

Fix: #473 
- Check the size of default plutusops in `PlutusOps`. If the size doesn't match with the fetched costmodel size, use index nos as operation names.

Koios/Ogmios - IndexOutofBound exception for PlutusV3 cost models

---

address/src/main/java/com/bloxbean/cardano/client/address/Address.java
core/src/main/java/com/bloxbean/cardano/client/account/Account.java
core/src/main/java/com/bloxbean/cardano/client/account/AccountException.java
core/src/test/java/com/bloxbean/cardano/client/account/AccountTest.java
crypto/src/main/java/com/bloxbean/cardano/client/crypto/bip32/HdKeyGenerator.java
crypto/src/main/java/com/bloxbean/cardano/client/crypto/cip1852/CIP1852.java
crypto/src/test/java/com/bloxbean/cardano/client/crypto/cip1852/CIP1852Test.java
hd-wallet/src/it/java/com/bloxbean/cardano/hdwallet/QuickTxBuilderIT.java
hd-wallet/src/it/java/com/bloxbean/cardano/hdwallet/StakeTxIT.java
hd-wallet/src/it/resources/log4j.xml
hd-wallet/src/main/java/com/bloxbean/cardano/hdwallet/Wallet.java
hd-wallet/src/main/java/com/bloxbean/cardano/hdwallet/supplier/DefaultWalletUtxoSupplier.java
hd-wallet/src/test/java/com/bloxbean/cardano/hdwallet/WalletTest.java
hd-wallet/src/test/java/com/bloxbean/cardano/hdwallet/supplier/DefaultWalletUtxoSupplierTest.java

- #482 Generate Account/Wallet from root prv key
- #471 Wallet: search utxos by address vkh

#482 Generate Account/Wallet from root prv key

---

README.md
docs/docs/gettingstarted/dependencies.md

Hi,
I updated a few more subpages of the docs to reflect the most recent version. Hopefully I have catched all occurences by now :-)

Update docs to recent version 0.6.3

---

backend/src/main/java/com/bloxbean/cardano/client/backend/api/DefaultUtxoSupplier.java
coinselection/src/main/java/com/bloxbean/cardano/client/coinselection/UtxoSelectionStrategy.java
coinselection/src/main/java/com/bloxbean/cardano/client/coinselection/UtxoSelector.java
coinselection/src/main/java/com/bloxbean/cardano/client/coinselection/impl/DefaultUtxoSelector.java
core-api/src/main/java/com/bloxbean/cardano/client/api/AddressIterator.java
core-api/src/main/java/com/bloxbean/cardano/client/api/UtxoSupplier.java
core-api/src/main/java/com/bloxbean/cardano/client/api/common/AddressIterators.java
function/src/main/java/com/bloxbean/cardano/client/function/TxBuilderContext.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/BalanceTxBuilders.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/ChangeOutputAdjustments.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/CollateralBuilders.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/ScriptBalanceTxProviders.java
function/src/main/java/com/bloxbean/cardano/client/function/helper/SignerProviders.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/ChangeOutputAdjustmentsTest.java
hd-wallet/src/it/java/com/bloxbean/cardano/hdwallet/QuickTxBaseIT.java
hd-wallet/src/it/java/com/bloxbean/cardano/hdwallet/QuickTxBuilderIT.java
hd-wallet/src/it/java/com/bloxbean/cardano/hdwallet/ScriptTxIT.java
hd-wallet/src/it/java/com/bloxbean/cardano/hdwallet/StakeTxIT.java
hd-wallet/src/main/java/com/bloxbean/cardano/hdwallet/DefaultWallet.java
hd-wallet/src/main/java/com/bloxbean/cardano/hdwallet/Wallet.java
hd-wallet/src/main/java/com/bloxbean/cardano/hdwallet/util/HDWalletAddressIterator.java
hd-wallet/src/test/java/com/bloxbean/cardano/hdwallet/WalletTest.java
hd-wallet/src/test/java/com/bloxbean/cardano/hdwallet/util/HDWalletAddressIteratorTest.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/AbstractTx.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/QuickTxBuilder.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/ScriptTx.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/verifiers/OutputAmountVerifier.java
quicktx/src/main/java/com/bloxbean/cardano/client/quicktx/verifiers/TxVerifiers.java

#490 
- The `UtxoSelectionStrategy` interface has been updated to accept an `AddressIterator` instead of a single address. This is required for HDWallet implementations, where the wallet needs to scan multiple addresses for UTXOs. For the existing single address mode, the `AddressIterator` only contains one address.
- An interface for the wallet and a default wallet implementation have been created. This will enable us to introduce new wallet implementations, such as `LedgerHWWallet` in the future without changing the core transaction builder APIs.
- A new method in `UtxoSupplier` and `UtxoSelector` to enable/disable utxo search by address vkh.

Wallet as fee payer / collateral payer in ScriptTx + UtxoSelectionStrategy interface change to handle multiple addresses

---

backend-modules/blockfrost/src/main/java/com/bloxbean/cardano/client/backend/blockfrost/service/OgmiosTxResponseParser.java
backend-modules/ogmios/src/it/java/com/bloxbean/cardano/client/backend/ogmios/OgmiosBaseTest.java
backend-modules/ogmios/src/it/java/com/bloxbean/cardano/client/backend/ogmios/OgmiosEpochServiceIT.java
governance/src/main/java/com/bloxbean/cardano/client/governance/GovId.java
governance/src/main/java/com/bloxbean/cardano/client/governance/LegacyDRepId.java
governance/src/test/java/com/bloxbean/cardano/client/governance/GovIdTest.java
quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/GovernanceTxIT.java
supplier/ogmios-supplier/src/main/java/com/bloxbean/cardano/client/supplier/ogmios/dto/ProtocolParametersDto.java
transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/governance/DRep.java

- New static methods in `GovId` to get DRep from drepId, Credential from ccHotId and ccColdId
- Fixed BFBackend's tx evaluator endpoint to parse & map `proposing` redeemer tag
- `OgmiosEpochService` :  Added required values like govActionDeposit, drepDeposit to the response.

Utility methods to convert CIP129 DRepId, cc ids + Fix Ogmios Tx Evaluator and Epoch Params

---

transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/Asset.java
transaction-spec/src/main/java/com/bloxbean/cardano/client/transaction/spec/MultiAsset.java
transaction-spec/src/test/java/com/bloxbean/cardano/client/transaction/spec/MultiAssetSpecTest.java
transaction-spec/src/test/java/com/bloxbean/cardano/client/transaction/spec/ValueSpecTest.java

If second operand contains:
1. an additional asset within a multi asset which is not present in the first operand
2. and additional multi asset which is not present in the first operand
The subtraction skips them, instead of setting them as negative in the resulting value.

[FIX] Fixed Value subtractions with extra assets or multi assets in second operand

---

function/src/main/java/com/bloxbean/cardano/client/function/helper/InputBuilders.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/InputBuildersTest.java
quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxV3IT.java

#510 
This PR fixes an issue where `ScriptTx.withChangeAddress(address, datum)` was converting datum objects to datum hashes instead of adding them as inline datums to change outputs. 
When using the QuickTx API to create script transactions with change outputs, the datum provided via `withChangeAddress()` was being converted to a datum hash rather than being included as an inline datum:
```java
// Example usage
ScriptTx scriptTx = new ScriptTx()
.collectFrom(utxo, plutusData)
.payToAddress(receiver, amount)
.withChangeAddress(scriptAddress, plutusData);  // plutusData was converted to hash
```
Modified `InputBuilders` to properly support both inline datums and datum hashes in change outputs:
1. Updated the core method signature to accept both datum types:
```
public static TxInputBuilder …
```

 Fix: Add support for inline datum in change outputs when using ScriptTx.withChangeAddress(address, datum)

---

function/src/main/java/com/bloxbean/cardano/client/function/helper/InputBuilders.java
function/src/test/java/com/bloxbean/cardano/client/function/helper/InputBuildersTest.java
quicktx/src/it/java/com/bloxbean/cardano/client/quicktx/ScriptTxV3IT.java

#510 
This commit backports the fix for inline datum support in change outputs from the main branch to the `release_0.6.x` branch.
- Modified InputBuilders.createFromUtxos() to properly handle inline datums in change outputs
- When a datum object is provided via ScriptTx.withChangeAddress(), it's now added as an inline datum instead of being converted to a datum hash
- Maintained backward compatibility with existing datum hash functionality
Details : https://github.com/bloxbean/cardano-client-lib/pull/511

[Backport] Fix: Add support for inline datum in change outputs when using ScriptTx.withChangeAddress()
